name: Cleanup Preview Resources

on:
  pull_request:
    types: [closed]

env:
  NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
  NEON_PROJECT_ID: ${{ secrets.NEON_PROJECT_ID }}

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Delete Neon branch
        run: |
          # Get PR number directly from GitHub context
          PR_NUMBER=${{ github.event.pull_request.number }}
          
          echo "PR Number: $PR_NUMBER"
          BRANCH_NAME="preview-pr-${PR_NUMBER}"
          echo "Branch Name to delete: $BRANCH_NAME"
          
          # Delete the Neon branch
          node scripts/db-migration-manager.js delete-branch $BRANCH_NAME
          
          echo "Deleted Neon branch: $BRANCH_NAME"

      - name: Comment on PR
        uses: actions/github-script@v6
        continue-on-error: true
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              const prNumber = context.issue.number;
              const branchName = `preview-pr-${prNumber}`;
              
              await github.rest.issues.createComment({
                issue_number: prNumber,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `🧹 Cleanup completed! 
                
                The Neon database branch \`${branchName}\` has been deleted.`
              });
              console.log('Comment added successfully');
            } catch (error) {
              console.log('Failed to add comment, but continuing: ' + error.message);
            } 