name: Preview Deployment

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
  NEON_PROJECT_ID: ${{ secrets.NEON_PROJECT_ID }}

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create Neon branch
        id: create-branch
        run: |
          # Get PR number directly from GitHub context
          PR_NUMBER=${{ github.event.pull_request.number }}
          echo "PR Number: $PR_NUMBER"
          BRANCH_NAME="preview-pr-${PR_NUMBER}"
          echo "Branch Name: $BRANCH_NAME"
          
          # Create a new branch in Neon (or use existing one)
          node scripts/db-migration-manager.js create-branch main $BRANCH_NAME
          
          # Set output for later steps
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Run migrations
        run: |
          # Run Prisma migrations on the new branch
          # Use db push instead of migrate for preview environments
          # This avoids the "schema not empty" error
          # Load DATABASE_URL from .env.local
          export $(grep DATABASE_URL .env.local | xargs)
          npx prisma db push

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Set DATABASE_URL in Vercel
        id: set-db-url
        run: |
          # Get the connection string from .env.local - properly extract just the value
          DB_URL=$(grep DATABASE_URL .env.local | cut -d '=' -f 2- | tr -d '"' | tr -d ' ')
          echo "Database URL extracted: $DB_URL"
          
          # Add to Vercel environment
          vercel env add DATABASE_URL "$DB_URL" preview --token=${{ secrets.VERCEL_TOKEN }}
          
          # Save the DB_URL for later steps
          echo "db_url=$DB_URL" >> $GITHUB_OUTPUT
          
          # Create a .env file in the project root with the DATABASE_URL
          echo "DATABASE_URL=$DB_URL" > .env
          
          # Also add it to the Vercel environment files
          echo "DATABASE_URL=$DB_URL" >> .vercel/.env.preview.local
          
          # Display environment for debugging
          echo "Contents of .env:"
          cat .env
          echo "Contents of .vercel/.env.preview.local:"
          cat .vercel/.env.preview.local

      - name: Set Clerk Authentication Variables in Vercel
        run: |
          # Create a temporary .env file with Clerk variables
          echo "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}" >> .vercel/.env.preview.local
          echo "CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }}" >> .vercel/.env.preview.local
          echo "NEXT_PUBLIC_CLERK_SIGN_IN_URL=/admin/login" >> .vercel/.env.preview.local
          echo "NEXT_PUBLIC_CLERK_SIGN_UP_URL=/admin/login" >> .vercel/.env.preview.local
          echo "NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=/admin" >> .vercel/.env.preview.local
          echo "NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=/admin" >> .vercel/.env.preview.local
          
          # Also add these to the root .env file
          echo "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}" >> .env
          echo "CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }}" >> .env
          echo "NEXT_PUBLIC_CLERK_SIGN_IN_URL=/admin/login" >> .env
          echo "NEXT_PUBLIC_CLERK_SIGN_UP_URL=/admin/login" >> .env
          echo "NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=/admin" >> .env
          echo "NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=/admin" >> .env

      - name: Build Project Artifacts
        env:
          DATABASE_URL: ${{ steps.set-db-url.outputs.db_url }}
        run: |
          # Print environment variables for debugging
          echo "DATABASE_URL environment variable: $DATABASE_URL"
          
          # Create a .env.production file with the DATABASE_URL
          echo "DATABASE_URL=$DATABASE_URL" > .env.production
          
          # Run the build
          vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Preview to Vercel
        id: deploy
        env:
          DATABASE_URL: ${{ steps.set-db-url.outputs.db_url }}
        run: |
          DEPLOYMENT_URL=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})
          echo "deployment_url=$DEPLOYMENT_URL" >> $GITHUB_OUTPUT

      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const deploymentUrl = '${{ steps.deploy.outputs.deployment_url }}';
            const branchName = '${{ steps.create-branch.outputs.branch_name }}';
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 Preview deployment is ready! 
              
              - Deployment URL: ${deploymentUrl}
              - Neon Database Branch: ${branchName}
              
              This preview has its own isolated database branch. Any schema changes or data modifications will not affect the main database.`
            }) 