name: Production Deployment

on:
  push:
    branches:
      - main

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
  NEON_PROJECT_ID: ${{ secrets.NEON_PROJECT_ID }}

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Set DATABASE_URL for production
        id: set-db-url
        run: |
          # Set the production DATABASE_URL from secrets
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env.local
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env
          echo "db_url=${{ secrets.DATABASE_URL }}" >> $GITHUB_OUTPUT
          
          # Display environment for debugging
          echo "Contents of .env:"
          cat .env

      - name: Run migrations on main branch
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          # Run Prisma migrations on the main branch
          node scripts/db-migration-manager.js migrate

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Set DATABASE_URL in Vercel
        run: |
          # Add to Vercel environment
          vercel env add DATABASE_URL "${{ secrets.DATABASE_URL }}" production --token=${{ secrets.VERCEL_TOKEN }}
          
          # Create a .env.production file with the DATABASE_URL
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env.production

      - name: Build Project Artifacts
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Production
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} 