name: Deploy Supabase Migrations

on:
  push:
    branches:
      - main
      - feature/*
    paths:
      - 'supabase/migrations/**'
  pull_request:
    paths:
      - 'supabase/migrations/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      # For pull requests, we'll just validate the migrations without applying them
      - name: Validate Migrations (Pull Request)
        if: github.event_name == 'pull_request'
        run: |
          echo "Validating migrations for pull request..."
          supabase link --project-ref "${{ env.SUPABASE_PROJECT_ID }}" -p "${{ env.SUPABASE_DB_PASSWORD }}"
          # Use --dry-run to validate without applying
          supabase db push --dry-run

      # For feature branch pushes, deploy to preview
      - name: Deploy Migrations (Preview)
        if: github.event_name == 'push' && github.ref != 'refs/heads/main'
        run: |
          echo "Deploying migrations to preview environment..."
          supabase link --project-ref "${{ env.SUPABASE_PROJECT_ID }}" -p "${{ env.SUPABASE_DB_PASSWORD }}"
          supabase db push

      # For main branch, deploy to production
      - name: Deploy Migrations (Production)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          echo "Deploying migrations to production environment..."
          supabase link --project-ref "${{ env.SUPABASE_PROJECT_ID }}" -p "${{ env.SUPABASE_DB_PASSWORD }}"
          supabase db push
