name: Deploy Supabase Migrations

on:
  push:
    branches:
      - main
      - feature/*
    paths:
      - 'supabase/migrations/**'
  pull_request:
    paths:
      - 'supabase/migrations/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
      
    steps:
      - uses: actions/checkout@v3

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Deploy Migrations (Preview)
        if: github.ref != 'refs/heads/main'
        run: |
          echo "Deploying migrations to preview environment..."
          supabase link --project-ref $SUPABASE_PROJECT_ID
          supabase db push

      - name: Deploy Migrations (Production)
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Deploying migrations to production environment..."
          supabase link --project-ref $SUPABASE_PROJECT_ID
          supabase db push
